--drop database carsharingDW
USE CarSharingDW

DROP TABLE RENTAL;
DROP TABLE "USER";
DROP TABLE RATING;
DROP TABLE MISCELLANEOUS;
DROP TABLE "DATE";
DROP TABLE "TIME";
DROP TABLE CITY;
DROP TABLE EQUIPMENT;
DROP TABLE CAR;
DROP TABLE WEATHER;